### ISSUE TITLE
use default table for default language

### ISSUE THREAD

**Issue by darynl** [globalize/globalize#266]
Is there a way to use the default table's values for the default language? like in Veger's fork for globalize2? And if not where can I start to make modifications in order to mimic it? I'm using Rails 3.2.12

**Comment by scarfacedeb** [comment]
@parndt @simi I think, it's ok to close it now

**Comment by rvsingh** [comment]
In version 5 do we have any configuration for this?

**Comment by tomash** [comment]
@rvsingh version 5 first release will be only about compatibility with Rails5, see #485

I remember this was globalize's behaviour long time ago (use original model table for default language), I also remember it was dropped due to some very serious technical reasons. If the developer wants less SQL queries executed, this is where joins-translation recommendation kicks in.
