### ISSUE TITLE
undefined method `create_translation_table!'

### ISSUE THREAD

**Issue by wnm** [globalize/globalize#369]
I tried to setup a fresh rails app with globalize, following the instructions:

```
rails new globalize_test_app
```

new file in app/models/post.rb with this content:

``` ruby
class Post < ActiveRecord::Base
  translates :title

end
```

create new migration:

```
rails g migration post
```

replace with this content:

``` ruby
class Post < ActiveRecord::Migration
  def up
    create_table :posts do |t|
      t.timestamps
    end
    Post.create_translation_table! :title => :string
  end
  def down
    drop_table :posts
    Post.drop_translation_table!
  end
end
```

running 

```
rails db:migrate
```

gives me:

```
undefined method `create_translation_table!'
```

also here is the code:
https://github.com/wnm/globalize_test_app

**Comment by phansch** [comment]
This is a bit of an edge case but it took me a while until I found out the cause. Maybe someone else stumbles upon this when preparing an upgrade to Rails 5 and will find it useful. I previously made sure that all my models inherit from `ApplicationRecord` instead of `ActiveRecord::Base` and when trying to run the migrations I got the error from above.

This happened because I re-defined the model in other migrations before the failing migration.

So essentially I had a correct model:

```ruby
# app/models/location.rb
class Location < ApplicationRecord
  translates :title
end
```
And a correct migration:

```ruby
# db/migrate/add_translation_table_for_locations.rb
class AddTranslationTableForLocations < ActiveRecord::Migration
  def up
    Location.create_translation_table!({:title => :string}, migrate_data: true)
  end

  def down
    Location.drop_translation_table!(migrate_data: true)
  end
end
```

But also this migration which runs before:
```ruby
# db/migrate/some_other_migration.rb
class Location < ActiveRecord::Base; end

class SomeOtherMigration < ActiveRecord::Migration
  def change
    # do something  
  end
end
```

Rails never picked up the actual model and the migration code only knew about the redefined model, which doesn't use the `translates` method. I guess this is because the two class definitions have two different superclasses, but I'm not sure.
The solution is to change all `ActiveRecord::Base` to `ApplicationRecord` in the migrations, and then Rails will load the correct model during the migration.
