### ISSUE TITLE
translation table for UUID as primary key

### ISSUE THREAD

**Issue by yoshi-iketani** [globalize/globalize#428]
hi,

I use Globalize gem for my rails 4.2 project, and the table primary ID is UUID in postgre.

Here is the table migration codes and created translation table foreign key is integer type, not UUID.

```
class CreateMessageThreads < ActiveRecord::Migration
  def up

    enable_extension 'uuid-ossp'

    create_table :message_threads, id: :uuid do |t|
      t.integer :resource_id, null: false
      t.string :resource_type, null: false
      t.datetime :deleted_at

      t.timestamps null: false
    end

    MessageThread.create_translation_table!({
      :title => :string
    })

  end

  def down
    drop_table :message_threads
    MessageThread.drop_translation_table!
  end
end
```

Is there a way to make this UUID work??

cheers

**Comment by daniel-de-wit** [comment]
I also needed this functionality and found followed this stackoverflow: http://stackoverflow.com/questions/28985568/ruby-on-rails-4-2-with-globalize-gem-for-uuid-table

Then I modified the example to reference the delegated model to check its primary key type instead of hard coding it. 

```
model.columns_hash[model.primary_key].type.to_sym
```

So basicly the edited method looks like this:

```
def create_translation_table(type = :id)
  connection.create_table(translations_table_name, id: model.columns_hash[model.primary_key].type.to_sym) do |t|
    t.uuid table_name.sub(/^#{table_name_prefix}/, '').singularize + "_id", :null => false
    t.string :locale, :null => false
    t.timestamps
  end
end
```

I know this isn't a very good solution, but maybe someone can pick this idea up?

**Comment by risinglf** [comment]
+1

**Comment by hengsokly** [comment]
+1
