### ISSUE TITLE
Fallbacks not working

### ISSUE THREAD

**Issue by mcmegavolt** [globalize/globalize#443]
**Gemfile**
```ruby
rails 3.2.21
globalize 3.1.0
```
**application.rb**
```ruby
config.i18n.default_locale = :uk
config.i18n.fallbacks = true
```
```ruby
$ I18n.locale = :ru
$ p = Article::Page.new
$ ...
$ p.title
=> "Title"
$ I18n.locale = :ru
$ p.title
=> nil
```

**Comment by alexander-ruehle** [comment]
+1

**Comment by parndt** [comment]
Thanks for reporting this; is there, by any stroke of luck, any way that you could write a failing test case for this bug?

**Comment by alexander-ruehle** [comment]
I take back my +1. This is not an issue caused by globalize, at least for me.
If you switch the `I18n.default_locale` at runtime the `I18n.fallbacks` hash stays the same and all translation fallbacks behave the same.
Clearing out the `I18n.fallbacks` hash on `I18n.default_locale` change solved the problem for me.
Im sorry for pushing this issue.
