### ISSUE TITLE
Validate presence true not working on locales

### ISSUE THREAD

**Issue by jandresrodriguez** [globalize/globalize#483]
I'm working on a rails project with globalize, where I've a model called Product like this:

```
class Product < ActiveRecord::Base

  translates :name, :description

  validates :name, presence: true

end
```

The problem is that the validates is not working for the update on other locales, it's working on the first create method, but whenever I want to update the object with another locale, it doesn't check for the presence of name. Example below:

```
Product.create!
   (0.3ms)  BEGIN
   (0.2ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: Name can't be blank
```

Once a Product is created and has en translations, when trying to update for another locale, the validators aren't checked, example:

```
irb(main):009:0> p.update_attributes(name: "", locale: :es)
   (0.2ms)  BEGIN
   (0.1ms)  COMMIT
=> true
```

Any thoughts on how this can be acheived?

**Comment by carlesjove** [comment]
I'm struggling with this too. Some people suggest using [another gem](https://github.com/globalize/globalize-accessors) to validate translations, however this will validate all translations at once, instead of only the one being updated.

I'm trying to build a custom validator, but I'm finding no way to access the `locale` attribute within the list of attributes. My idea was to

`content.update title: "Translated title", locale: :ca`

and then have a validator that performs `validates :title_ca, presence: true`. But since I can't a way to access the locale being edited, I'm stuck.

I guess that a lot of folks run into the validations problems, so it'd be nice if we can figure out some default way to handle this…

**Comment by nyddogghr** [comment]
+1

I was having the same issue. My model needs a name and description. The creation is ok, but for each new locale, I can set name and descriptions to be empty without any exception to be raised.

I have found this workaround:
```
class Container < ActiveRecord::Base
  translates :name, :description
  Container::Translation.include(Secure)
  Container::Translation.attr_accessible(:name, :description, :locale, :as => :renderer)
  validates :name, presence: true, length: {minimum: 3, maximum: 255}
```
becomes
```
class Container < ActiveRecord::Base
  translates :name, :description
  Container::Translation.include(Secure)
  Container::Translation.attr_accessible(:name, :description, :locale, :as => :renderer)
  class Translation
    validates :name, presence: true, length: {minimum: 3, maximum: 255}
  end
```

Tell me if this is in fact the only correct way

**Comment by nozpheratu** [comment]
To add to @nyddogghr comment, I'm guessing something like this is also required on the parent model:

```ruby
validates_associated :translation
```

I don't really like this, it feels pretty hacky.

**Comment by obahareth** [comment]
I looked through a bunch of issues related to this one and uniqueness (#386, #483, #358, and others). 

I tried all the solutions mentioned in them:

The simple validation most of us start from doesn't work:
```ruby
class Container < ActiveRecord::Base
  translates :name, :description
  validates :name, presence: true, length: {minimum: 3, maximum: 255}
end
```

This proposed solution didn't work:
```ruby
class Container < ActiveRecord::Base
  translates :name, :description

  class Translation
    validates :name, presence: true, length: {minimum: 3, maximum: 255}
  end
```

This one didn't work either:
```ruby
class Container < ActiveRecord::Base
   translates :name, :desc
   accepts_nested_attributes_for :translations, :allow_destroy => true

  validates_associated :translations
  translation_class.validates :name, uniqueness: true, presence: true
end
```

I even tried using [globalize-accessors](https://github.com/globalize/globalize-accessors) as some have suggested but I haven't been able to get validations working with globalize translated attributes. Does anybody have any suggestions or fixes?

**Comment by bustikiller** [comment]
I wrote a custom validator to check the presence of a translated attribute in all languages for my Rails application:

`multilang_presence_validator.rb`

```
ActiveRecord::Base.class_eval do

  def self.validates_attr_present_in_all_languages(*attr_names)
    options = attr_names.extract_options!
    validates_each(attr_names, options) do |record, attribute, value|

      contents = I18n.available_locales.map { |locale| record.send("#{attribute}_#{locale}".to_sym) }

      record.errors[:base] << "#{record.class.human_attribute_name attribute} #{I18n.t('errors.general.all_languages_required')}" if contents.any?{|c| c.blank?}
    end
  end
end
```

And I use it like:

`validates_attr_present_in_all_languages :name, :description`

Hope it helps

**Comment by mauriciopasquier** [comment]
I'm also stuck with this issue. The general consensus I've seen around is "don't validate". I don't think that's acceptable in some (most?) cases, though.

**Comment by WaKeMaTTa** [comment]
I'm also stuck with this issue also. :(

**Comment by nyddogghr** [comment]
To complete my previous answer here, I've found a solution that I'm satisfied with. 
I've added 2 validations in a globalized concern, added on my translated models.
Here are the complete validations I have:
* In my model, I've completed Translation class to validate the presence of name (prevents empty name)
```
Class Toto
  translates :name
  include Globalized
  Class Translation
    validates :name, :presence => true
  end
end
```
* Validate on create only (object not persisted) that my model has a name and the current locale is one of my fallback locales (in the format 'fr,en,it')
* Validate on destroying a translation that there is at least one remaining translation in one of the fallback locales (used for removing the translation for one locale only, not for destroying the object)
```
module Globalized
  include ActiveSupport::Concern

  included do |base|
    validate :validate_fallback_locale, :if => Proc.new { |o| !o.persisted? }
    def validate_fallback_locale
      if self.name.nil? || !ENV['I18N_FALLBACKS'].split(',').include?(I18n.locale.to_s)
        self.errors.add(:base, 'nope')
      end
    end
  end

  class self::Translation
      validates :locale, :presence => true, :format => {:with => LOCALE_REGEXP}
      before_destroy do
        has_fallback_locale = self.globalized_model.translations
          .where(:locale => ENV['I18N_FALLBACKS'].split(',') - [self.locale.to_s])
          .any?

        if !has_fallback_locale
          raise Api::Exception::ValidationError
        end
      end
    end
  end
end
```
I'm don't say it fixes the issue, but I've had no empty name since using this for several months.
Hope it helps.
