### ISSUE TITLE
How to properly drop a translation

### ISSUE THREAD

**Issue by donatoaz** [globalize/globalize#493]
I think it would be nice if the README had a step by step on how to remove translations from a column. I honestly am having a hard time, because I need to migrate from a non-default locale to the main table (how to do this via a rake task?)

**Comment by shioyama** [comment]
Just to clarify, you have a translated attribute that you want to convert back to a normal attribute? If so that will involve throwing away translations in all but one locale.

**Comment by cecilian** [comment]
Hi there, I see this issue has not had any activity recently but I am having the same problem (I think).

Basically I have a model with a translated field
```
class Quota < ActiveRecord::Base
  translates :title
end
```

And I would like to remove the translation, i.e. return to using the `quotas.title` field on the original model.

Now from the documentation it seems it would be possible to use a migration like the following:
```
class UntranslateQuotas < ActiveRecord::Migration
  def up
    Quota.drop_translation_table! migrate_data: true
  end

  def down
    Quota.create_translation_table!({
      title: :string
    }, {
      migrate_data: true
    })
  end
end
```

This migration runs fine *if the model has the* `translate :title` *line*.
However if the model has that line, the application does not work properly because doing anything with a `Quota` prompts globalize to look for the translation table, which is no longer there.

On the other hand, if I remove the `translate :title` line first, the migration won't run:
```
StandardError: An error has occurred, this and all later migrations canceled:
undefined method `drop_translation_table!' for #<Class:0x007fd052b751e0>
```

So it seems that in one's own development environment it is possible to make it work by performing the migration first and modifying the model later, but what is unclear is how to proceed in the production environment where this mode of action is not really possible.

**Comment by cecilian** [comment]
So it seems the solution is easy enough, the `translate :title` line has to be put in the migration itself:

```
class UntranslateQuotas < ActiveRecord::Migration
  def up
    Quota.translates :title
    Quota.drop_translation_table! migrate_data: true
  end

  def down
    Quota.translates :title
    Quota.create_translation_table!({
      title: :string
    }, {
      migrate_data: true
    })
  end
end
```
This way it is possible to run the migration even if the translation has already been removed from the model file.

I can do a PR for documenting this more clearly if it is ok for the maintainers.
