### ISSUE TITLE
Release Rails 5 compatible Gem

### ISSUE THREAD

**Issue by trcarden** [globalize/globalize#543]
Can someone please cut a rails 5 compatible gem and place it on ruby gems? The last build is from Feb and only supports Rails 4

**Comment by awaltman** [comment]
+1

**Comment by minifast-julia** [comment]
+1

**Comment by SergeyKolenko** [comment]
+1

**Comment by jonian** [comment]
+1

**Comment by thaneros** [comment]
+1

**Comment by simi** [comment]
Better than +1 will be to provide some feedback. Please can you point your projects to master branch and run specs and do some smoke tests to ensure we can release without breaking your applications?

I think there are still some Rails 5 related problems (latest one I'm aware of -> https://github.com/globalize/globalize/pull/546).

**Comment by Circuit8** [comment]
+1

**Comment by shioyama** [comment]
The inverse issue is fixed in #551. What other issues were there?

**Comment by shioyama** [comment]
I've [tagged](https://github.com/globalize/globalize/issues?q=is%3Aissue+is%3Aopen+label%3Arails5) all the issues related to rails5 compatibility and fixed a few of them (e.g. #551, #555).

**Comment by shioyama** [comment]
Ok I don't see any more rails5-specific issues, but we really need some people to use master in their applications to ensure there are no issues before we release this. Let's give a few more days and then if we see no issues I think we can release 5.10.

**Comment by shioyama** [comment]
Sorry seems there's one issue left to fix: #502. There was a fix in #503 that could be used, although no regression spec.

**Comment by fschwahn** [comment]
So, I've been using globalize with rails5 on commit 7d507472e4076c720d798736137eb28d169eb1a1 and everything I was using was working fine. I did a bundle update to commit b44a06dedcb096c3afa8f6b79464fdea917c1480 and suddenly StrongParameters stopped working (I do `model.attributes = params.require(:model).permit(:column)`).  I suppose commit 4ea5cf73184ad441f665219f456f005ee75debf2 is to blame.

**Comment by dalpo** [comment]
@fschwahn thanks for reporting!
Could you open a new issue with more informations about this?

**Comment by shioyama** [comment]
Ah maybe it's that `return unless new_attributes.is_a?(Hash)`, which I took verbatim from the rails 4 source, but [looks like](https://github.com/shioyama/rails/blob/72f97e281059bc983eef5bc8915e53249c623dff/activerecord/lib/active_record/attribute_assignment.rb#L9) in Rails 5 `attributes=` is just an alias for `assign_attributes`, maybe something goes wrong there.

**Comment by jdugarte** [comment]
I switch to master to test this, and the only issue I'm getting is this deprecation warning:

DEPRECATION WARNING: Method symbolize_keys is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.0.1/classes/ActionController/Parameters.html (called from assign_attributes at /Users/dugarte/.gem/ruby/2.3.1/bundler/gems/globalize-b44a06dedcb0/lib/globalize/active_record/instance_methods.rb:21

**Comment by shioyama** [comment]
@jdugarte Thanks, that should be an easy fix.

Anybody else notice anything with the latest `master`?

**Comment by sasselin** [comment]
Will it be released when?

**Comment by rhymes** [comment]
Any news?

**Comment by shioyama** [comment]
For the record, there are two issues holding up release of a Rails 5 version, #519 (with potential fix in #571) and compatibility with `friendly_id`, discussed in [this comment](https://github.com/globalize/globalize/issues/562#issuecomment-260354605).

The latter conflict with FriendlyId is quite tricky because it gets back to a tricky issue: I figured out that many issues with the [query methods hack](https://github.com/globalize/globalize/blob/e1cbe4247458c13b344738a682609d23eba53f65/lib/globalize/active_record/query_methods.rb#L1) were due to the translated attribute column being on both the translation table *and* the model table. This is apparently a very common configuration, but it makes it very difficult to do things like `Post.where(title: "foo")` and get AR to correctly understand that it should look for "foo" in `post_translations` and not `posts`. So I added a deprecation warning in #557 and made the code in Rails 5 ignore the column on the model table.

The problem is that the [friendly_id-globalize](https://github.com/norman/friendly_id-globalize) gem requires the column to be on *both* tables. So we basically have to choose: either we drop support for that gem, or we have to revert changes and deal with the unpredictable consequences of having the same column on both model and translation tables. I'm *really* loathe to take the latter path, I think it makes the query methods stuff much more fragile. See #560 to see some of the code changes I reverted by assuming the column was not on the model table.

I personally think we should just give up on support for compatiblity with `friendly_id` since the gem doesn't seem to be supported anyway, but I'd like to hear other opinions...

**Comment by basex** [comment]
[friendly_id-globalize](https://github.com/norman/friendly_id-globalize) haven't been maintained for 2 years and it's quite small. I suggest not making the code more complex and create unpredictable consequences for compatibility with that gem. It should be friendly_id-globalize trying to work around the problem.

**Comment by joelmichael** [comment]
Last published version isn't just from February, but February 2015. This code has been maintained in master since then and apparently we have to track master to use this gem. Can't imagine why the author prefers this.

**Comment by shioyama** [comment]
@basex @joelmichael Thanks, I agree we should just give up on compatibility with FriendlyId. For the record, it wasn't the author who was reporting the problem but a user (@anthony-robin).

**Comment by klaustopher** [comment]
I just looked at the [gemspec](https://github.com/norman/friendly_id-globalize/blob/master/friendly_id-globalize.gemspec) of the `firendly_id-globalize`gem and they don't even add `globalize` as a runtime dependency 😲 .

The maintainers of `friendly_id` and `friendly_id-globalize` seem to be active on GitHub. Maybe they can release a version of the gem, that specifies the 5.0 releases of globalize and release the current state of `5.1.0` as `6.0` since it breaks compatibility.

Then everybody who's on Rails 5 (not requiring `friendly_id`) could upgrade to the 6.0.0 version of `globalize` and everybody else could stick with the old 5.0.x release (like we are all forced to right now)

**Comment by alisaifee** [comment]
Based on the current master (https://github.com/globalize/globalize/commit/e1cbe4247458c13b344738a682609d23eba53f65) I'm still facing a few issues with globalize and rails 5. I've created a sample application which demonstrates all of these:
- repo: https://github.com/honestbee/rails-5-migration-issues
- travis: https://travis-ci.org/honestbee/rails-5-migration-issues

**Comment by leoi11** [comment]
also additional note for the initial post:
> The last build is from Feb **2015** and only supports Rails 4

**Comment by siegy22** [comment]
It's almost 2 years since the last release..
Can I do anything to release a new (rails 5 compatible) version?

**Comment by shioyama** [comment]
@alisaifee I took a quick look at the repository with rails 5 issues. [This](https://github.com/honestbee/rails-5-migration-issues/blob/f289bdeb1e864c31f20e231f847e67eaccc20b6c/spec/models/brand_spec.rb#L14) one, where it looks like the record has only one translation when it should have two, is caused by the `default_scope` [here](https://github.com/honestbee/rails-5-migration-issues/blob/f289bdeb1e864c31f20e231f847e67eaccc20b6c/app/models/brand.rb#L9) on your `Brand` model. If you remove the scope, you will see that both translations are actually saved.

So: `Brand.includes(:translations).first.translations` will return both translations, but `Brand.includes(:translations).order(id: :asc).translations` will only show the first translation. I'm not sure why that is but I'm guessing it's a Rails change rather than a Globalize issue.

Haven't had time to look at the other issues yet, will try to soon.

**Comment by shioyama** [comment]
@siegy22 Help would be: narrow down remaining issues and solve them, or at least provide failing tests like @alisaifee has done.

**Comment by shioyama** [comment]
@alisaifee I've added a failing spec for [this issue](https://github.com/honestbee/rails-5-migration-issues/blob/f289bdeb1e864c31f20e231f847e67eaccc20b6c/spec/models/product_spec.rb#L11) in #586.

Although creating an entire repository with an application and failing specs is great, ideally failing tests on this repository are best and are harder to ignore :smile: 

Haven't dug further into this one but it looks thorny to me...

**Comment by shioyama** [comment]
@alisaifee Regarding the issue in #586, I've distilled the spec down to what I think is the core problem, which seems to be that if you have two models with a has-many-through relationship, and they both have translations *with the same name* (in my spec, `name`, in yours it was `title`), then you get this error. At least this seems to be the case.

If the spec in #586 is isolating the issue, this should make it easier to fix.

**Comment by shioyama** [comment]
Ah never mind, the issue is again with `default_scope`  [here](https://github.com/honestbee/rails-5-migration-issues/blob/f289bdeb1e864c31f20e231f847e67eaccc20b6c/app/models/category.rb#L10). #586 was failing because I was missing a column.

So I think at least two of the specs you identified are related to `default_scope`; remove that and the specs pass for me at least.

**Comment by fschwahn** [comment]
According to the activerecord changelog the only change in rails 5 to default scopes was this: https://github.com/rails/rails/pull/23666/files#diff-eab65420b920f3e7e96cdcd636471979

Would be interesting to see if the specs are still failing in rails5 if this change is reverted.

**Comment by shioyama** [comment]
@alisaifee I've looked at the other failing specs in [the migration issues repo](https://github.com/honestbee/rails-5-migration-issues) and they seem to be non-globalize issues. [This] controller params spec has nothing to do with Globalize as far as I can tell, it's just a rails upgrade change. [This](https://github.com/honestbee/rails-5-migration-issues/blob/master/spec/models/department_spec.rb#L8) model spec is failing because the default scope has `:name` which is a translated attribute; I don't really know why this passed previously (probably difference between AR 4 and 5) but it really shouldn't, the scope should be on the translation table if you're referencing a column on that table.

[This](https://github.com/honestbee/rails-5-migration-issues/blob/master/spec/models/product_spec.rb#L21) serialization test may be a Globalize issue. I don't think Globalize should ever really have supported this type of thing but the specs do include serialization stuff. Personally I'd prefer not to support this out of the box actually, it seems really hacky, but you may be right that this is a regression.

**Comment by alisaifee** [comment]
Sorry for the late response, only just found enough time to update the [rails-5-migration-issues ](https://github.com/honestbee/rails-5-migration-issues) repository with some work arounds / discoveries.

I've created a [workarounds](https://github.com/honestbee/rails-5-migration-issues/commits/workarounds) branch which contains all the commits needed to resolve the pending issues I was seeing. 

* [Serialization issue](https://github.com/honestbee/rails-5-migration-issues/commit/4f5707730ddc286ccae2538b8562a628358ef91d) - as you mentioned, it shouldn't really have been a globalize supported feature. I just switched the column type to `json`
* [Default Scope Issue for updating translated attribute][https://github.com/honestbee/rails-5-migration-issues/commit/7d601c15338ec2230c4668b15697d6fd20440b2c] - I could only get the desired result by getting rid by using an explicit scope
*  [Default Scope issue with join table](https://github.com/honestbee/rails-5-migration-issues/commit/352b5c999d09b282f10f9346d9be7031b75edc69)

That alone wasn't enough to fix the issues and something in [rails 5.0.1](https://github.com/rails/rails/compare/v5.0.0.1...v5.0.1) - tipped the scale to fix these [last two errors](https://travis-ci.org/honestbee/rails-5-migration-issues/jobs/199831400) related to the error about the model being marked read only.

With the above patches, I am no longer seeing any issues in our application with `rails 5.0.1` + [globalize@5b0ff2c92e7536f908dc82a4c2a15b04be79e821](https://github.com/globalize/globalize/commit/5b0ff2c92e7536f908dc82a4c2a15b04be79e821)

**Comment by miks** [comment]
So, can anybody finally release a new gem version?

**Comment by miks** [comment]
bump

**Comment by alisaifee** [comment]
@miks I think it will be more beneficial if you can share a version from github that you've tested with your use of globalize to create more confidence in terms of compatibility with rails 5

**Comment by miks** [comment]
I don't get it. Globalize itself does not have tests against rails5?

**Comment by miks** [comment]
And I don't think that this is somehow related to rails5. Last globalize release was on february 15, 2015.
Really, there hasn't been any bugfixes and improvements since then?
Looks like no one really care about releasing new version as for regular project you can simply use gem from github.
My problem is that I use globalize in another gem... and have no possibilities to push new globalize gem release.

**Comment by shioyama** [comment]
@dalpo If we ignore the friendly_id thing, the last issue I know of is #519 with the fix in #571. I'm a bit uncomfortable with the fix since it adds so much code. I'm more inclined honestly to revert #489 since it's a fairly narrow use case, or maybe finding some way to fix it differently.

Any thoughts?

Also @miks yes there have been many changes since the last release in 2015. The problem is that there is no real "owner" of Globalize, just a few people like myself who contribute here and there. I've tried to fix the remaining issues that I could in the time I have but releasing a new version means a flood of new people will come with new issues, and we'll be having the same complaints about not fixing issues ("but the last version worked fine!"), etc.

Also, yes there are tests but Globalize is heavily tied to AR so changes in the latter affect the former in unpredictable ways. So there will always be things that you only see after launching.

That being said, I think we should just release and if people have issues they can lock to the current version for now. We should probably update the changelog when we do.

@globalize/collaborators What do you think?

**Comment by ridiculous** [comment]
@shioyama we could also release a preview or beta version 💃

**Comment by parndt** [comment]
@shioyama I'm happy with having a beta release if people want to target their gemspec files at it, what do you think?

I'm also happy with updating `friendly_id-globalize` with whatever needs to be done.

**Comment by miks** [comment]
beta version gem release is very good option imho.

**Comment by miks** [comment]
So, can we just release beta version finally?

**Comment by parndt** [comment]
@miks if you see previous messages, i.e. the one from @shioyama you can see that there are a couple of remaining issues #519 / #571.  I know that as a gem consumer this can be frustrating but when code gets released into the world with bugs we then get a lot of issues opened telling us so.  I've just been able to allocate time to this task and have merged #571 so now we're okay for a beta.

I think in future we'll aim to use the new mobility gem but that'll be a major version change.

**Comment by parndt** [comment]
https://rubygems.org/gems/globalize/versions/5.1.0.beta1

**Comment by shioyama** [comment]
For reference: https://github.com/shioyama/mobility

It can already handle the same table structure as Globalize, mostly same API, but is not a 100% drop-in replacement. Globalize could refactor to use it under the hood. Also supports translatable columns, jsonb, etc. etc.

More info: http://dejimata.com/2017/3/3/translating-with-mobility

**Comment by shioyama** [comment]
Thanks @parndt !!!

**Comment by dalpo** [comment]
Thanks @parndt @shioyama for your great work! :tada:

**Comment by zedtux** [comment]
When will the beta version be stable?

**Comment by parndt** [comment]
Nobody's test reported back to us their opinion on the matter 😄

**Comment by klaustopher** [comment]
I have never ran into any of the issues that were described here, so I cannot give feedback on those. 

But we have been using a forked version of 5.0 since last year and have switched to 5.1.0.beta1 on march 10th and have been running this in production since than without any problems. I don't know if that feedback helps, but there are real world apps out there, that are using this version without any problems.

**Comment by thomasdarde** [comment]
I also do use it in production since the days of the release of "5.1.0.beta1" without problem. Keep the great work and a big than you !

**Comment by parndt** [comment]
Awesome! Thank you!

Before a final, I'll work to get Travis CI passing again because it's hard to maintain with it doing that.  

I've queried this commit 607e6ef3 but if anyone has any inclination to investigate that'd help us out a lot! 😄

**Comment by shioyama** [comment]
@parndt Commented on 607e6ef. No time to look into it now but `ignored_columns` must not be working.

**Comment by parndt** [comment]
Thanks @shioyama
