### ISSUE TITLE
Eager loading with fallback

### ISSUE THREAD

**Issue by Obi-TOB** [globalize/globalize#570]
Hi,

I have been fighting with this for quite some time in different circumstances. When I break it down it comes to this:

I have a model

```
class Test< ActiveRecord::Base
  translates :name
end
```

I have two languages and set up the fallback in both direction:

```
Globalize.fallbacks = {:en => [:en, :de], :de => [:de, :en]}
```

When I create instances in different languages

```
I18n.locale = :en
t = Test.new(name: "t English")
I18n.locale = :de
t.name = "t German"
t.save
t2 = Test.create!(name: "t2 German")
```

the fallbacks work as expected:

```
I18n.locale = :en
t.name # => "t English"
t2.name #=> "t2 German"

I18n.locale = :de
t.name # => "t German"
t2.name #=> "t2 German"
```

However when loading all translated instances (which happens a lot, especially when eager loading) I get only the subset of instances of the respective language

```
Test.all.with_translations(:de) # => [t,t2], because both languages exist
Test.all.with_translations(:en) # => [t], because there's no translation for t2
```

Is there are a way to get the fallback translations as well when eager loading, e.g. something like

```
Test.all.with_fallback_translations(:en)
=> [t,t2], where t has the English and t2 has the fallback German translation
```

I saw the same issue in the context of ordering https://github.com/globalize/globalize/issues/439.

Do you have a suggestion how to solve this in general? (Ideally with bidirectional fallbacks?)

I can write the corresponding sql, but I have around 10 models with translations and I think I cannot be the first to encounter this issue...

Any good (i,e. preformant) solution would be highly appreciated.

**Comment by Obi-TOB** [comment]
Hi,

In the meantime I have come up with this (same case as above).

Logic is
- join an additional table that containing the "correct" entries from the translations_table 
- from this table we need only team_id and the locale to filter down from all translations)
- this table is created using a simple MAX on the translations together with a GROUP BY

In SQL (to illustrate the logic)
```
  SELECT t.id, tt.name, tt.locale
    FROM test t
    JOIN test_translations tt on tt.team_id = t.id
   -- the join below preselect the translation id_s we want 
   -- (assumption here default lang: de, fallback lang: en)
    JOIN (SELECT test_id,
		 CASE 	WHEN MAX(CASE 	WHEN locale = 'de' then 1 -- default language
					WHEN locale = 'en' then 0 -- fallback
				 END) = 1 THEN 'de'
			ELSE 'en' 
		 END as locale
	   FROM test_translations tt
	  GROUP BY test_id ) pref on pref.test_id = tt.test_id and pref.locale = tt.locale
```
I brought this back to my models and made it dynamic so that I can use it as scope in all of my models:
- get the translations_table_name dynamically
- create the name of the foreign key dynamically
- use Globalize.fallbacks[x] to get active and fallback language

```
  with_fallback_translations    { 
     joins(:translations)
     .joins("INNER JOIN (
               SELECT #{fk_column},
                 CASE
                   WHEN MAX(CASE
                              WHEN locale = '#{Globalize.fallbacks[0]}' then 1 -- default language
                              WHEN locale = '#{Globalize.fallbacks[1]}' then 0 -- fallback
                            END) = 1
                   THEN '#{Globalize.fallbacks[0]}'
                   ELSE '#{Globalize.fallbacks[1]}'
                 END as pref_loc
               FROM #{self.translations_table_name}
              GROUP BY #{fk_column} ) pref ON pref.#{fk_column}= #{translations_table_name}.#{fk_column}
                                          AND pref.pref_loc = #{translations_table_name}.locale") }

  def self.fk_column
    self.to_s.downcase + '_id'
  end
  
```
I'm sure this can be beautified :)

What I like least is that it uses joins and doesn't allow to use "includes" anymore, (However in any case I have never really understood how ActiveRecord determines when to use a join and when to use a seperate query using include). If someone can pinpoint me  in the right direction, I might think about further work here.

**Comment by shioyama** [comment]
Hmm... this looks pretty tricky. I'm not marking it as a "bug" because I don't think it really is one, more of a limitation of `with_translations`. I don't think we'll be able to support it, but maybe someone can do some magic with arel to make it work?

**Comment by rainchen** [comment]
@Obi-TOB +1 same case here. you're my hero, saved my day

**Comment by santostiago** [comment]
Did you get a better solution than this one?
It does work (yey!!) but the process is slow.

I've done it with `coalesce` which is an order of magnitude faster. The problem is, to keep it working with the gem, I need to call the relationship by the same name as the translations table.
All would be good if `globalize` didn't add the `joins` when we sort the translations fields.
For instance, if we do `MyClass.order(:translated_field)` it will always add the `inner join translation_table`.

I'm checking the code of the gem to figure out how to solve this.
Anyway, my code is as follows:

```
scope :with_fallback_translations, -> { 
    joins(
        "INNER JOIN (
            SELECT #{self.table_name}.id, #{coalesce_string}
            FROM #{self.table_name}
            LEFT JOIN #{self.translations_table_name} original ON #{self.table_name}.id = original.#{fk_column} AND original.locale = '#{Globalize.fallbacks[0]}'
            LEFT JOIN #{self.translations_table_name} fallback ON #{self.table_name}.id = fallback.#{fk_column} AND fallback.locale = '#{Globalize.fallbacks[1]}'
          ) #{self.translations_table_name} ON #{self.translations_table_name}.id = #{self.table_name}.id
        ")
}
```

**Comment by ppostma** [comment]
@Obi-TOB & @santostiago, thanks for sharing your solutions!

I've edited the code to make it work in my environment (e.g. `attribute_types` was not defined) and refactored it a bit. Also, I've added `preload(:translations)` so all translations will be loaded in a separate query.

Since we need this in a few different places, I've created a concern for it which I'm sharing here: https://gist.github.com/ppostma/00ce0085d18fabf3f2444200225f01a4

Still a problem that @santostiago also mentions is when using `order`, globalize automatically adds an `inner join translation_table`. We solved this by prefixing the column with the table name, like this:

`MyClass.with_fallback_translations.order("#{MyClass.translation_class.table_name}.title")`
