### ISSUE TITLE
PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint

### ISSUE THREAD

**Issue by manjeetsbhatkar** [globalize/globalize#582]
Getting such issue even after removing not-null contrain from "name" column.

**Comment by ridiculous** [comment]
Which version are you using? Do you have the "name" column on both the primary table and translation table? If so, did you remove the constraint on both of them? Globalize will try to write to only the translation table, unless you specify otherwise with the `:fallbacks_for_empty_translations` setting

**Comment by manjeetsbhatkar** [comment]
Thanks ridiculous.
My bad. Now I have removed not-null constraint from development and test environment and its working for me.
I have one more question like is that(removing not null constrain) only way to avoid this error?

**Comment by crazymykl** [comment]
This is a regression from Globalize 4.x.
