### ISSUE TITLE
ActiveRecord with Globalize -  find vs where

### ISSUE THREAD

**Issue by akshantalpm** [globalize/globalize#585]
**We are using Globalize gem version 0.3.0 and Ruby 1.9 with Rails 3.2** 

If I fire the following query:

`Post.find_by_title('some_title').to_sql`

The resulting value is:

`SELECT DISTINCT `posts`.id FROM `posts` LEFT OUTER JOIN `post_translations` ON `post_translations`.`post_id` = `posts`.`id` WHERE `post_translations`.`locale` IN ('de', 'en', 'pt', 'zh-CN') AND (post_translations.name IS NOT NULL) AND ((`post_translations`.`title` = 'some_title' AND `post_translations`.`locale` IN ('en', 'zh-CN', 'de', 'pt'))) LIMIT 1`

But if I try the following:

Post.where(title: 'some_title').to_sql

I get the following:
`SELECT `posts`.* FROM `posts`  WHERE `posts`.`name` = 'some_title'`

Any reasoning behind this behavior?

**Comment by CaioBianchi** [comment]
@akshantalpm Interesting given that `find_by` is pretty much just an alias for `where` according to the [source](https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by).

Difference being that `where` returns an `ActiveRecord::Relation` containing one or more records matching the parameters, whereas `find_by` will return a `DISTINCT` record.

The fact that `find_by` returns `nil` instead of an empty hash for empty results may have also been a factor in the author's approach.
