### ISSUE TITLE
Not compatible with Rails Attributes API

### ISSUE THREAD

**Issue by ansonhoyt** [globalize/globalize#611]
Globalize 5.1.0.beta1 has been working well for us. We are having our first real trouble when using the [Rails Attributes API](http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute) to manage an attribute that is also being translated. If I don't translate the attribute, my custom type's `cast` method is called (as expected), but it stops working when I activate translations.

Given that the Attributes API is pretty new, I'm not sure if this is a bug or a feature request. I'd like to use them both together.

Using your template, here's a test case that reproduces the issue. You can see it passing without translations by commenting out `  translates :content, :title` and re-running (since I also defined :title on the posts table).

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '5.0.2'
gem 'globalize', '5.1.0.beta1'
gem 'sqlite3'
require 'active_record'
require 'globalize'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    # Defined title here too. Works as expected if we don't translate :title
    t.string     :title
  end

  create_table :post_translations, force: true do |t|
    t.references :post
    t.string     :title
    t.text       :content
    t.string     :locale
  end
end

class AllcapsType < ActiveRecord::Type::String
  def cast(value)
    value&.upcase # capitalize the value
  end
end

class Post < ActiveRecord::Base
  translates :content, :title
  attribute :title, AllcapsType.new
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: 'hi')

    assert_equal 'HI', post.title
  end
end
```

**Comment by thebravoman** [comment]
Hi @ansonhoyt 
Have you found a solution to this?

**Comment by ansonhoyt** [comment]
I think we just avoided it. Don't recall the details, but would still love to have this gem work with an attribute.

**Comment by npflood** [comment]
I'm jumping in on this one. When using Simple_Form I was getting the wrong field type when referring to translated fields. This was a direct result of the Attribute's type being missing. I ended up monkey patching Simple_Form back to the "column_for_attribute" method of determining column types instead of the new "type_for_attribute" method. +1 for getting the new method working.

**Comment by lazyatom** [comment]
I've dug into this a little, and I think I understand at least what we'd need to fix to make Globalize compatible with the attributes API, if not exactly how to implement those fixes.

For illustration, let's consider this code, paraphrased from the attributes API documentation at the time of writing.

```ruby
class MoneyType < ActiveRecord::Type::Integer
  def cast(value)
    if !value.kind_of?(Numeric) && value.include?('$')
      price_in_dollars = value.gsub(/\$/, '').to_f
      super(price_in_dollars * 100)
    else
      super
    end
  end

  def deserialize(value)
    if value
      "DB$%.2f" % (value / 100.0)
    end
  end
end

ActiveRecord::Type.register(:money, MoneyType)

class Item < ActiveRecord::Base
  attribute :translated_price_in_cents, :money
  translates :translated_price_in_cents
end
```

This type lets us supply the `translated_price_in_cents` attribute as a string like `$9.37`, and will make sure we store the actual number of cents (`937`). And for the sake of clarity, when we load a record back from the database, it will show the `translated_price_in_cents` attribute as having the value `DB$9.37`, just to demonstrate type casting in the other direction. Finally, we're "translating" this attribute, so that we can store different values of it for different locales.

To illustrate what's going on, we can consider the lifecycle of an object in four phases: building a new object, saving it to the database, loading it from the database and finally querying against a record.

### Building a new object

```ruby
item = Item.new(translated_price_in_cents: '$9.37') # => #<Item:0x00007ff1e69f0e68>
item.translated_price_in_cents # => "$10.00"
```

*Problem*: assigning the value doesn't perform any type casting.

*Explanation*: The main reason why this doesn't work is because, for translated attributes, Globalize provides a different implementation to `write_attribute`. In a normal `ActiveRecord` object, this method will end up calling `@attributes.with_value_from_user`, which uses the type information that the attribute system defines to do casting. In the globalise version, it basically just stores the value in a hash.

### Saving a record

```ruby
item.save # => true
item.translated_price_in_cents # => 0

*Problem*: the value stored in the database is wrong

*Explanation*: The way that Globalize ends up storing its translations is via the autosave association mechanism in Rails, along with a callback to `save_translations!`, which is called on the translation instance itself (e.g. an instance of `Item::Translation`). In this method, we iterate through all of the attributes, calling `write_attribute` on the translation instance to set the value on the record before it gets saved. Because we're calling `write_attribute` on a record that doesn't define translations (remember, we're on the translation class, not the main class), this actually _does_ invoke behaviour that handles the attributes API, but no types end up being set on that class; they're only set on the main class. So, the translation class casts the value (`$10.00`) using the default type, which then tries to turn this string into an integer and gets the value `0`.

This gives us a hint to one part of the fix.

### Loading a record

```ruby
item.reload # => #<Item:0x00007ff1e69f0e68>
item.translated_price_in_cents # => 0

Globalise doesn't really get hugely in the way here; when we load a record from the database, it simply clears out the translated attributes and then reloads everything via ActiveRecord. However, because there's no attribute API information on the translation class, it loads translated attributes using the default types, and so the `deserialize` method we would hope for is never called, and we get whatever value was stored in the database.

#### Fix part one

If we add some behaviour to `translates` to "copy" attribute type settings for translated attributes into the translation class, then this goes some way towards fixing this part of the lifecycle.

```ruby
class Item < ActiveRecord::Base
  attribute :translated_price_in_cents, :money
  translates :translated_price_in_cents
  translation_class.attribute :translated_price_in_cents, :money
end

item = Item.new(translated_price_in_cents: '$9.37') # => #<Item id: nil, translated_price_in_cents: "$9.37">
```

So we can see this doesn't fix the initial build; the only way to fix that will be to add type casting support into the `write` method in the globalise adapter. However:

```ruby
item.save # => true
item # => #<Item id: 1, translated_price_in_cents: "DB$9.37">
```

We can now see here (and if we peek in the DB) that our type finally _was_ invoked, and we successfully stored the raw value `937` in the database. Also, our outbound casting was invoked, as demonstrated by the attribute value `DB$9.37`).

We can get this behaviour automatically if we augment the `translates` method to check the record being called to look for anything set in the `attribute_types` on the base record, and set the same types in the translation class.

There's a question of whether or not to require all `attribute` calls to be made before the `translates` call, or to be more flexible in permitted order, at the expense of more patching of the ActiveRecord API.

Regardless, in the short term, users of Globalize might be able to fix basic issues by just calling `translation_class.attribute <name>, <type>` underneath their calls to `translates`

However, there's still an important case left...

### Querying against a record

One of the features that the attributes API provides is seamless translation for querying as well as assignment. However, even with the fix above in place, the following doesn't work:

```ruby
Item.where(translated_price_in_cents: '$9.37') # => #<ActiveRecord::Relation []>
```

The reason this happens is more complex.

In a normal (non-translated) query involving the attributes API, when the query is built using `ActiveRecord::Relation::PredicateBuilder`, it determines the Area object for table being used for the query (`items` in this case), and then checks whether or not the attributes being used in any of the conditions have any types. It's pretty simple in this case, because there are no intermediate tables.

However, when we query using a translated attribute, globalize rewrites the condition for us, so

```ruby
Item.where(translated_price_in_cents: '$9.37')
```

becomes

```ruby
Item.where('item_translations.translated_price_in_cents' => '$9.37')
```

This takes the ActiveRecord query builder along a different code pathway, translating the query again to `{item_translations: {translated_price_in_cents: '$9.37'}}`, and then ultimately invoking `associated_predicate_builder(:item_translations)`. Within this method call, ActiveRecord attempts to determine the actual association we are referring to, using reflections, so that it can them figure out the Arel table and do things like type casting. And this is where we hit what is arguably a bug in Rails.

In `associated_predicate_builder`, ActiveRecord calls `table.associated_table` with what it understands from the query to be the association name, `'item_translations'. If this was successful, it would return table metadata object representing the translations, which could then be queried to do things like type casting.

_However_, here's the problem: our query is specifying `item_translations` as the table name, but the _association_ is called `translations`, so when Rails tries to find the table via reflection, it fails, and no type casting happens.

The reason I think this might be a bug in Rails is that I believe there's a chance this will happen when any dot-syntax query passes through ActiveRecord; any query like `Item.where('other_table.column' => 'value')` is likely to not work with the attributes API unless there's also an association with the exact name `other_tables` on the `Item` class. However, we're right at the fringes of expected functionality here.

#### Fix part two... ish

There are a couple of ways this could be fixed. One would be for Globalize to change the association name it uses from `translations` to `item_translations` (or whatever exactly matches the translation table name). This is a potentially breaking change and it might impact other parts of Globalize in ways I can't predict. It might be possible to define the association twice, once as `translations` and another as `item_translations`? Again, I'm not 100% sure of the impact of doing that, beyond it ensuring that there's a matching reflection to determine the table metadata.

Another option would be to fix this part of Rails, such that it attempts to reflect on the associations not only by association name, but also by underlying table name, thus allowing `Item._reflect_on_association('item_translations')` to return the "has_many" reflection for the `translations` association. Likewise, this is changing the behaviour of a fairly low-level part of Rails which might have consequences for code that only expects reflections to exist by exact association name.

Another option would be to change Globalize's condition rewriting to use the association name, rather than the table name, e.g. changing `.where(translated_price_in_cents: '$9.37')` to `.where('translations.translated_price_in_cents' => '$9.37')`. This fails at the moment because while Rails correctly finds the table and does the type case, and Globalize correctly ensures we join against the translations table, we end up with a query in the form `SELECT ... INNER JOIN item_translations ... WHERE translations.translated_price_in_cents = 1000` -- the join table doesn't match the `translations` table referenced in the `WHERE` part of the query.

Anyway, that's what I've found so far. Hopefully this is useful, and I'm still considering possible fixes, which if successfully I'll certainly push back up here.
