### ISSUE TITLE
unknown attribute 'locale' in create

### ISSUE THREAD

**Issue by basex** [globalize/globalize#685]
There is a regression bug on the master. Not sure if related with updates to globalize or to activerecord.

```ruby
Comment.where(post_id: 10, user: 'test').create #=> works ok
Post.find(10).comments.where(user: 'test').create #=> ActiveModel::UnknownAttributeError: unknown attribute 'locale' for Comment.
```

Seems to be failing in https://github.com/globalize/globalize/blob/8a193c1272c3640e516ef36ac78e5d634152d3a5/lib/globalize/active_record/attributes.rb#L10

gem 'activerecord', '5.2.0'
gem 'globalize', '5.1.0' - master

**Comment by n-rodriguez** [comment]
> Not sure if related with updates to globalize or to activerecord.

I would say both ^^ Actually AR 5.2 tries to set the `locale` attribute on the `Comment` model but fails because this attribute doesn't exist... There is a test covering this case.

You can chek by yourself by adding this method on your `Comment` model :
```ruby
def locale=(locale)
  puts 'Hello!'
  @locale = locale
end
```

The weird thing is that AR 5.1.6 does exactly the same without failing :/

**Comment by n-rodriguez** [comment]
Hi! Can you please test with this fork : https://github.com/n-rodriguez/globalize on the `wip/appraisal` branch?  Thank you!

**Comment by matthv** [comment]
I had the same issue and your fork fixed it !

**Comment by basex** [comment]
@n-rodriguez thanks a lot. Your code fixed the problem.

Can you do a pull request?

**Comment by n-rodriguez** [comment]
https://github.com/globalize/globalize/pull/686
