### ISSUE TITLE
Rails 6.1 support?

### ISSUE THREAD

**Issue by poudelprakash** [globalize/globalize#770]
Last stable version is v5.3.0, which has dependency of 
```
  s.add_dependency 'activerecord', '>= 4.2', '< 6.1'
  s.add_dependency 'activemodel', '>= 4.2', '< 6.1'
```
This makes it unusable with rails 6.1, any plans of new release to address?

**Comment by Migoo** [comment]
Hello, 
We got the same issue in our project. Any release planned soon ?

**Comment by tomash** [comment]
Hi,
as discussed in #753 and README, we (maintainers) are open to pull requests but there's not much of an active development from our side. I'll be happy to assist anyone who wants to work on such PR, I don't think AR API has changed in 6.1 (at least in the parts that Globalize is using) so it might be just a matter of changing version numbers in dependencies and running the test suite 😎

**Comment by tomash** [comment]
Nope, the test suite has a few failures both with ActiveRecord 6.0 and 6.1. It seems dirty attribute tracking API has changed in 6.0. I'll look into it.

**Comment by tomash** [comment]
It's a deeper one. Not very hard but will require a bit of work in `Globalize::ActiveRecord::AdapterDirty` and its test. I think I'll find the time to do it over this weekend.

**Comment by pixeltrix** [comment]
@tomash I've been looking at this since Rails 6.1 came out since I need it to complete an upgrade project and I've created a draft PR (#771) - have a look and let me know what you think.

**Comment by tomash** [comment]
@pixeltrix this looks good at a first glance, I'll check it later on my dev machine. Failed builds for older versions and lots of branching in the code make me think we should just release Globalize version for Rails 6.0 and 6.1 without any compatibility with older versions, maybe just make a git branch if something needs backporting for previous versions of Globalize (the ones for ActiveRecord < 6).

**Comment by pixeltrix** [comment]
@tomash do you mean the builds on the PR? Looks like they've all failed due to an issue with the setup-ruby action - I'll see if there's something I need to tweak (will also add 2.7 to the matrix).

In terms of support I would suggest to aim for Rails 5.2, 6.0 and 6.1 since they're the currently supported versions for security fixes.

**Comment by pixeltrix** [comment]
@tomash all the checks are now passing (though with a lot of warnings about deprecations, etc.)

**Comment by parndt** [comment]
Released as version 6.0.0 🎉

**Comment by padavanocskos** [comment]
Hi, I try to upgrade spree 4.2.
globalize 6.0.0
rails 6.1
spree_core 4.2.1

After bundle install run rake db:create, but i give this error:
Unable to connect to a database. Globalize skipped ignoring columns of translated attributes.

Does anyone have any idea about this error?

**Comment by pixeltrix** [comment]
@padavanocskos if you're saying that `rails db:create` in Rails 6.1 with the latest version of Globalize doesn't work then I'd suggest opening a new issue rather than piggybacking on this one that's now closed - however it seems unlikely that Globalize would prevent connecting to the database so I'd look at what's causing that error.
